#!/bin/bash
# This simple script is used to auto generate makefile for a c or cpp or go file
file=$1
[[ -f "makefile" ]] && rm 'makefile'; touch 'makefile'
#[[ -f "makefile" ]] || touch "makefile"
echo "src = $file" >> makefile
echo "out = ${file%.*}" >> makefile
echo "${file%.*}: ${file}" >> makefile
echo "r:" >> makefile
case ${file#*.} in
	c) echo -e "\tgcc -o \$(out) \$(src)" >> makefile ;;
	cpp) echo -e "\tg++ -o \$(out) \$(src)" >> makefile ;;
	go) echo -e "\tgo build \$(src)" >> makefile ;;
	*) 	echo "can not judge file type, choose file again"
		rm makefile	
		echo "Generate makefile failedly!"
		;;
esac
echo -e "\t./\$(out)" >> makefile
echo "c:" >> makefile
echo -e "\trm ./\$(out)" >> makefile
echo "Generate makefile successfully!"
