#!/bin/sh

# The famous "get a menu of emojis to copy" script.
# Use rofi dmenu mode instead of dmenu
# Must have xclip installed to even show menu.
xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ~/Desktop/.hiddenfile/emoji | rofi -dmenu -location 1 -xoffset 10 -yoffset 32 -line-padding 4 -clumns 1 -width 20 -lines 10 -padding 25 -hide-scrollbar -i -p "pick an emoji" | sed "s/ .*//")

[ "$chosen" != "" ] || exit

# If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
	xdotool key Shift+Insert
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
