#!/bin/bash
# uses scrot, imagemagick, and i3lock to take a screenshot   of the current desktop, blur it, set that picture as background lock, and lock the 
# computer

#scrot -o ~/.cache/lock/lock.png

convert ~/.cache/lock/lock.png -blur 0x5.0 ~/.cache/lock/blurlock.png

i3lock -i ~/.cache/lock/blurlock.png --insidecolor=0000001c --ringcolor=0000003e \
        --linecolor=00000000 --keyhlcolor=ffffff80 --ringvercolor=ffffff00 \
        --separatorcolor=22222260 --insidevercolor=ffffff1c \
        --ringwrongcolor=ffffff55 --insidewrongcolor=ffffff1c \
        --verifcolor=ffffff00 --wrongcolor=ff000000 --timecolor=ffffff00 \
        --datecolor=ffffff00 --layoutcolor=ffffff00
