#!/bin/bash
# This script is used to change the background image randomly
#path="${HOME}/Pictures/BG_images/"
#num=$(ls $path | wc -l)
#let image="$[$RANDOM%100]"
#until [[ $image -le $num && $image -gt 0 ]]
#do
	#let image="$[$RANDOM%100]"
#done
#PI="$(ls $path | grep $image)"
#setbg $path$PI 2> /dev/null;
pathimage=$(find ~/Pictures/BG_images/ | shuf | head -n 1)
#setbg $pathimage 2> /dev/null;
echo $pathimage
