#!/bin/bash
id=$(xinput --list | grep Finger | cut -d '=' -f2 | awk '{print $1}') 
current_state=$(xinput list-props $id | grep -i "Device Enabled" | awk '{print $4}')
if [[ $current_state == '0' ]];then
	xinput set-prop $id "Device Enabled" 1
	notify-send "The touch screen has been turn on !"
else
	xinput set-prop $id "Device Enabled" 0
	notify-send "The touch screen has been turn off !"
fi

