#!/bin/bash
current_state=$(xinput list-props 22 | grep -i "Device Enabled" | awk '{print $4}')
if [[ $current_state == '0' ]];then
	xinput set-prop 22 "Device Enabled" 1
	notify-send "The touch screen has been turn on !"
else
	xinput set-prop 22 "Device Enabled" 0
	notify-send "The touch screen has been turn off !"
fi

